name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'

      - name: Build binaries
        run: |
          GOOS=windows go build -o bin/coffeecup.exe .
          GOOS=darwin go build -o bin/coffeecup-darwin .
          GOOS=linux go build -o bin/coffeecup-linux .
        env:
          GOARCH: amd64

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            bin/coffeecup.exe
            bin/coffeecup-darwin
            bin/coffeecup-linux
